---

- hosts: all
  tasks:
    - name: Install essential packages
      sudo: yes
      apt:
        update_cache: yes
        name: "{{ item }}"
      with_items:
        - golang
        - vim
        - build-essential
        - git
        - unzip
        - supervisor
        - python-setuptools

    - name: Download AWS cfn-bootstrap
      sudo: yes
      get_url:
        url: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
        dest: /usr/local/src/aws-cfn-bootstrap-latest.tar.gz

    - name: Prepare AWS cfn-bootstrap folder
      sudo: yes
      file:
        name: /usr/local/src/aws-cfn-bootstrap-latest
        state: directory

    - name: Extract AWS cfn-bootstrap
      sudo: yes
      shell: tar xvfz /usr/local/src/aws-cfn-bootstrap-latest.tar.gz --strip-components=1 -C /usr/local/src/aws-cfn-bootstrap-latest
      args:
        creates: /usr/local/src/aws-cfn-bootstrap-latest/setup.py

    - name: Install AWS cfn-bootstrap
      sudo: yes
      shell: easy_install /usr/local/src/aws-cfn-bootstrap-latest
      args:
        creates: /usr/local/bin/cfn-init

    - name: Ensure hello-app user
      sudo: yes
      user:
        name: hello-app
        shell: /bin/bash

    - name: Ensure hello-app directory
      sudo: yes
      file:
        path: /home/hello-app/go/src/github.com/lobsterdore
        state: directory
        recurse: yes
        owner: hello-app
        group: hello-app

    - name: Ensure hello-app log directory
      sudo: yes
      file:
        path: /home/hello-app/logs
        state: directory
        recurse: yes
        owner: hello-app
        group: hello-app

    - name: Copy hello-app from /tmp
      sudo: yes
      shell: "cp -R /tmp/hello-app/ /home/hello-app/go/src/github.com/lobsterdore/; chown -R hello-app:hello-app /home/hello-app/go/src/github.com/lobsterdore/"
      args:
        creates: /home/hello-app/go/src/github.com/lobsterdore/hello-app

    - name: Build hello-app
      sudo: yes
      sudo_user: hello-app
      command: "make build"
      environment:
        GOPATH: /home/hello-app/go
      args:
        chdir: /home/hello-app/go/src/github.com/lobsterdore/hello-app
        creates: /home/hello-app/go/bin/hello-app

    - name: Create supervisor config
      sudo: yes
      shell: "cp /tmp/hello-app/supervisor.conf /etc/supervisor/conf.d/hello-app.conf"
      args:
        creates: /etc/supervisor/conf.d/hello-app.conf
      notify:
        - Reread supervisor
        - Update supervisor

  handlers:
    - name: Reread supervisor
      sudo: yes
      command: supervisorctl reread

    - name: Update supervisor
      sudo: yes
      command: supervisorctl update
